import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;

public class Title {

  private static final Map<String, List<String>> titleExpertises = new TreeMap<>();

  static {
    List<String> advanceSkills = new ArrayList<>(Arrays.asList(
        "Java",
        "Spring Boot",
        "C++",
        "C#",
        ".Net",
        "React.js",
        "Flutter",
        "Apache Tomcat",
        "Backend",
        "Frontend",
        "DevOps",
        "Microsoft Azure",
        "Amazon Web Service",
        "Google Cloud Provider",
        "React Native",
        "Scrum",
        "Python",
        "Golang",
        "Xamarin",
        "Android",
        "iOS",
        "XCode",
        "VueJS",
        "ExpressJS",
        "JavaScript",
        "HTML",
        "CSS",
        "Apache Kafka",
        "Docker",
        "Kubernetes",
        "SQL",
        "NoSQL",
        "Git",
        "SVN",
        "JDBC",
        "Hibernate",
        "Groovy",
        "Scala",
        "TypeScript",
        "Ruby",
        "Kotlin",
        "Angular",
        "ASP.NET",
        "Django",
        "Laravel",
        "GraphQL",
        "Microservices",
        "Bootstrap",
        "Ember",
        "Swift",
        "Redux",
        "JavaFX",
        "Microsoft SQL Server",
        "PostgreSQL",
        "MySQL",
        "MongoDB",
        "Oracle",
        "Cassandra",
        "CouchDB",
        "Redis",
        "ElasticSearch",
        "DBA",
        "Neo4j",
        "Heroku",
        "Maven",
        "Gradle",
        "SonarQube",
        "CircleCI",
        "Ansible",
        "Jenkins",
        "JUnit",
        "ETL",
        "Oracle Warehouse",
        "Logi Info",
        "Pentaho",
        "Hadoop",
        "Spark",
        "AI",
        "ML",
        "System Analytic",
        "Batch script",
        "Waterfall",
        "Agile",
        "Kanban",
        "English",
        "Japanese",
        "French",
        "Atlassian JIRA",
        "AWS Redshift",
        "Backbone.js",
        "COBOL",
        "jQuery",
        "Linux",
        "Node.js",
        "Objective C",
        "PHP",
        "Perl",
        "R",
        "Ruby on Rails",
        "Shell script",
        "Spring Framework",
        "AJAX",
        "Bash",
        "ASP.NET Core",
        "Microsoft Visio",
        "Postman",
        "Confluence"
    ));
    List<String> normalSkills = new ArrayList<>(Arrays.asList(
        "Java",
        "Spring Boot",
        "C++",
        "C#",
        ".Net",
        "React.js",
        "Flutter",
        "Apache Tomcat",
        "Backend",
        "Frontend",
        "Microsoft Azure",
        "Amazon Web Service",
        "Google Cloud Provider",
        "React Native",
        "Scrum",
        "Python",
        "Golang",
        "Xamarin",
        "Android",
        "iOS",
        "XCode",
        "VueJS",
        "ExpressJS",
        "JavaScript",
        "HTML",
        "CSS",
        "Apache Kafka",
        "Docker",
        "Kubernetes",
        "SQL",
        "NoSQL",
        "Git",
        "SVN",
        "JDBC",
        "Hibernate",
        "Groovy",
        "Scala",
        "TypeScript",
        "Ruby",
        "Kotlin",
        "Angular",
        "ASP.NET",
        "Django",
        "Laravel",
        "GraphQL",
        "Microservices",
        "Bootstrap",
        "Ember",
        "Swift",
        "Redux",
        "JavaFX",
        "Microsoft SQL Server",
        "PostgreSQL",
        "MySQL",
        "MongoDB",
        "Oracle",
        "Cassandra",
        "CouchDB",
        "Redis",
        "ElasticSearch",
        "DBA",
        "Neo4j",
        "Heroku",
        "Maven",
        "Gradle",
        "SonarQube",
        "CircleCI",
        "Ansible",
        "Jenkins",
        "JUnit",
        "ETL",
        "Oracle Warehouse",
        "Logi Info",
        "Pentaho",
        "Hadoop",
        "Spark",
        "AI",
        "ML",
        "Batch script",
        "Waterfall",
        "Agile",
        "Kanban",
        "English",
        "Japanese",
        "French",
        "Atlassian JIRA",
        "AWS Redshift",
        "Backbone.js",
        "COBOL",
        "jQuery",
        "Linux",
        "Node.js",
        "Objective C",
        "PHP",
        "Perl",
        "R",
        "Ruby on Rails",
        "Shell script",
        "Spring Framework",
        "AJAX",
        "Bash",
        "ASP.NET Core",
        "Microsoft Visio",
        "Postman",
        "Confluence"
    ));
    List<String> testingSkills = new ArrayList<>(Arrays.asList(
        "Java",
        "C#",
        "DevOps",
        "Microsoft Azure",
        "Amazon Web Service",
        "Google Cloud Provider",
        "Scrum",
        "Python",
        "Automation test",
        "Manual test",
        "Android",
        "iOS",
        "JavaScript",
        "Apache JMeter",
        "Apache Kafka",
        "Docker",
        "Kubernetes",
        "SQL",
        "NoSQL",
        "Git",
        "SVN",
        "GraphQL",
        "Microservices",
        "Microsoft SQL Server",
        "PostgreSQL",
        "MySQL",
        "MongoDB",
        "Oracle",
        "Cassandra",
        "CouchDB",
        "Redis",
        "ElasticSearch",
        "Neo4j",
        "Jenkins",
        "JUnit",
        "Selenium",
        "Cucumber",
        "Serenity",
        "ETL",
        "QlikView",
        "Oracle Warehouse",
        "Logi Info",
        "Pentaho",
        "Hadoop",
        "Spark",
        "AI",
        "ML",
        "Batch script",
        "Waterfall",
        "Agile",
        "Kanban",
        "English",
        "Japanese",
        "French",
        "Karate",
        "Atlassian JIRA",
        "AWS Redshift",
        "Linux",
        "Shell script",
        "Bash",
        "Postman",
        "Confluence"
    ));
    List<String> businessSkills = new ArrayList<>(Arrays.asList(
        "Microsoft Azure",
        "Amazon Web Service",
        "Google Cloud Provider",
        "Scrum",
        "Python",
        "Manual test",
        "Android",
        "iOS",
        "Docker",
        "Kubernetes",
        "SQL",
        "NoSQL",
        "GraphQL",
        "Microservices",
        "Microsoft SQL Server",
        "PostgreSQL",
        "MySQL",
        "MongoDB",
        "Oracle",
        "Cassandra",
        "CouchDB",
        "Redis",
        "ElasticSearch",
        "Neo4j",
        "ETL",
        "QlikView",
        "Oracle Warehouse",
        "Logi Info",
        "AI",
        "ML",
        "Business Analyst",
        "Wireframe Development",
        "System Analytic",
        "Product Documentation",
        "Graphic Design",
        "Waterfall",
        "Agile",
        "Kanban",
        "Scrum master",
        "English",
        "Japanese",
        "French",
        "Atlassian JIRA",
        "Microsoft Visio",
        "Postman",
        "Confluence",
        "Mockup",
        "Oracle Business Intelligence",
        "Resource planning"
    ));
    titleExpertises.put("SA", advanceSkills);
    titleExpertises.put("SSE", advanceSkills);
    titleExpertises.put("SE", normalSkills);
    titleExpertises.put("QA", testingSkills);
    titleExpertises.put("SQA", testingSkills);
    titleExpertises.put("BA", businessSkills);
    titleExpertises.put("SBA", businessSkills);
  }

  public static Map<String, List<String>> getTitleExpertises() {
    return titleExpertises;
  }
}